# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: DotnetCore/SpidersNestNetCore
  displayName: 'dotnet build $(buildConfiguration)'
- script: 'npm test'
  workingDirectory: DotnetCore/SpidersNestNetCore/ClientApp
  displayName: 'dotnet test $(buildConfiguration)'
